# Generated by Django 4.2.6 on 2023-10-10 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0003_rename_link_product_domain_remove_product_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('PARSING', 'PARSING'), ('ERROR', 'ERROR'), ('OK', 'OK')], db_index=True, default='PARSING', max_length=30),
        ),
    ]
