# Generated by Django 4.2.5 on 2023-10-05 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'offers_offers',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OfferTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_status', models.CharField(choices=[('WAITING_DATA_PROCESSING', 'waiting_data_processing'), ('DATA_PROCESSING', 'data_processing'), ('WAITING_PARSING', 'waiting_parsing'), ('PARSING', 'parsing'), ('OK', 'ok'), ('ERROR', 'error')], default='WAITING_DATA_PROCESSING', max_length=30)),
            ],
            options={
                'db_table': 'offers_offer_tasks',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OfferTaskRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
                ('offer_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_task', to='offers.offertask')),
            ],
            options={
                'db_table': 'offers_offer_task_requests',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.IntegerField(default=77)),
                ('domain', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=1000)),
                ('status', models.CharField(choices=[('PARSING', 'PARSING'), ('ERROR', 'ERROR'), ('OK', 'OK')], db_index=True, default='PARSING', max_length=30)),
                ('data', models.JSONField(default=dict)),
                ('offer_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='offers.offertask')),
            ],
            options={
                'db_table': 'offers_products',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.AddField(
            model_name='offer',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='offers.product'),
        ),
    ]
